[drive]
type = "service_account"
project_id = "your-project-id"
private_key_id = "your-private-key-id"
private_key = """your-private-key"""
client_email = "your-client-email"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "your-client-cert-url"

folder_id = "your-folder-id"

[database]
# You can override this at runtime with DATABASE_URL to use a remote DB.
url = "postgresql://username:password@localhost:5432/database_name"

[mail]
email = "your-email@example.com"
api_key = "your-mail-api-key"

[app]
link = "your-app-link"
